# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

vars:
  CODE: application/ adapters/ domain/ infra/ presentation/ 

tasks:
  test:
    desc: Running tests
    cmds:
      - pytest -p no:cacheprovider
    silent: true

  "format":
    desc: Formatting code
    cmds:
      - echo "Start formating..."
      - ruff format {{.CODE}}
      - ruff check --fix {{.CODE}}
    silent: true

  "lint:mypy":
    desc: Linting code with mypy
    cmds:
      - echo "Linting code with mypy"
      - mypy {{.CODE}}
    silent: true

  "lint:ruff":
    desc: Linting code with ruff
    cmds:
      - echo "Linting code with ruff"
      - ruff check {{.CODE}}
    silent: true

  check:
    desc: Linting code
    silent: true
    cmds:
      - task lint:mypy
      - task lint:ruff
      - task format
      - task test

  "generate:migration":
    desc: Generate new migration file
    cmds:
      - echo "Generating new migration"
      - alembic revision --autogenerate {{.CLI_ARGS}}
    silent: true

  "migration:up":
    desc: Run all migrations
    cmds:
      - echo "Run migrations..."
      - alembic upgrade head
    silent: true